### ISSUE TITLE
Provide and document a convenient means of defining messengers

### ISSUE THREAD

**Issue by jacg** [jacg/nain4#109]
See also:

+ #14
+ #100

**Comment by gonzaponte** [comment]
I've been playing with the messengers again. We need to decouple the `n4::run_manager`'s initialization from the call to `.actions(...)`. This is needed because while `G4RunManager::SetUserInitialization` only instantiates the relevant classes, `G4RunManager::Initialize` calls some methods of said objects. Those methods can potentially use the variables set by messengers. Because the call to `G4RunManager::Initialize` is bound to the call to `.actions(...)`, the commands cannot be sent in between those two calls, which is what's needed. So in practice we will need something along the lines of

```
auto rm = n4::run_manager::create()
  .physics (...)
  .geometry(...)
  .actions (...);

ui.apply_command("/your/command/one   value1);
ui.apply_command("/your/command/two   value2);
ui.apply_command("/your/command/three value3);

rm.initialize();
```
This will require modifying `n4::ui`, I believe, but I haven't looked into that just yet.

**Comment by gonzaponte** [comment]
I have a first iteration of this in my branch `decouple-rm-init`, if you want to take a look. It doesn't seem to have much of an impact in our code so far, precisely because we never used messengers.

**Comment by jacg** [comment]
Is this done, now that we have merged 96ac1ea7359d384f49da06a5d587218be497d159?

**Comment by gonzaponte** [comment]
We have the flexibility to use G4 messengers properly now, although it's not very well documented[^1]. We still have #14 in the pipeline which aims at providing a better interface for messengers. They can be decoupled, but it's not clear to me if this issue was meant to cover only the first part or all of it.

[^1]: Documentation in general is lacking, but the resources are limited.

**Comment by jacg** [comment]
I think that this issue was opened to ensure we address @Aretno's problems with messengers (#100). I think we have done that now.

The documentation still needs doing.  Maybe that should be added to #120, or immediately be given an issue of its own. But I would like to close this one, to record that we have done something significant.

**Comment by gonzaponte** [comment]
Ok, added to #120.
