### ISSUE TITLE
Fix LSP

### ISSUE THREAD

**Issue by jacg** [jacg/nain4#121]
LSP support was broken somewhere along the line .

We have no idea how to write an automatic test for this!

This needs to be fixed ASAP, as it hugely degrades developer productivity.

**Comment by gonzaponte** [comment]
The culprit is e9c27fabb54f5fcef4d778b529f1206f5d4acf5f Separate nain4 & tests CMakeLists. I found a workaround that may give us a hint of what's wrong:

If I do `ln -s nain4/compile_commands.json compile_commands.json` in `nain4/build`, LSP comes back to life. I suspect that `clangd` might have the search paths hardwired somewhere. For reference, see [this](https://releases.llvm.org/8.0.0/tools/clang/tools/extra/docs/clangd/Installation.html#compile-commands-json). It is not very explicit, but it gives us a hint that `clang` is not looking for the file where we put it.

If we don't have a better alternative, we can always copy the file with `cmake` or `just`. I wouldn't waste too much time on this, though.

**Comment by jacg** [comment]
I wouldn't call it wasting time. If we ever get back to writing C++ (as opposed to spending all our time hacking cmake list files, bash snippets, Nix expressions and GHA workflows) not having C++ LSP working properly out of the box is going to slow us down considerably.

**Comment by jacg** [comment]
> For reference, see [this](https://releases.llvm.org/8.0.0/tools/clang/tools/extra/docs/clangd/Installation.html#compile-commands-json). It is not very explicit, but it gives us a hint that `clang` is not looking for the file where we put it.

Acutally, it seems very explicit:

>  Clangd will look for [`compile_commands.json`] in the parent directories of the files you edit.

and 

> compile_commands.json will be written to your build directory. You should symlink it (or copy it) to the root of your source tree, if they are different.
>
> ```sh
> $ ln -s ~/myproject/compile_commands.json ~/myproject-build/
> ```

although both your hack and the above link example seem inconsistent with the text: 

+ they say: You should [copy it] to the root of your source tree
+ they do: [copy it] from the root of the project to the build tree
+ you do: [copy it] from somewhere in the build tree to somewhere else in the build tree

**Comment by gonzaponte** [comment]
> Acutally, it seems very explicit

Yes. I meant that it's not very explicit in listing *all* the locations where it looks for the file, as clearly, it's not only in the root directory.

> although both your hack and the above link example seem inconsistent with the text:
>
>    they say: You should [copy it] to the root of your source tree
>    they do: [copy it] from the root of the project to the build tree
>    you do: [copy it] from somewhere in the build tree to somewhere else in the build tree

Yup. Copying to / Linking it from the root dir seems to be the safest, as it is the only one documented, so I would go for that.

> I wouldn't call it wasting time. If we ever get back to writing C++ [...] not having C++ LSP working properly out of the box is going to slow us down considerably.

Indeed. I meant we shouldn't waste too much time in finding the best solution. Having a stable solution is good enough, IMO.

**Comment by gonzaponte** [comment]
I have another solution. Adding a file `.clang` in the root dir with:
```
CompileFlags:
  CompilationDatabase: nain4/build/nain4
```

seems to work
